<script src="<?= asset('app/js/jquery.min.js') ?>"></script>
    <script src="<?= asset('app/js/jquery-migrate-3.0.1.min.js') ?>"></script>
    <script src="<?= asset('app/js/popper.min.js') ?>"></script>
    <script src="<?= asset('app/js/bootstrap.min.js') ?>"></script>
    <script src="<?= asset('app/js/jquery.easing.1.3.js') ?>"></script>
    <script src="<?= asset('app/js/jquery.waypoints.min.js') ?>"></script>
    <script src="<?= asset('app/js/jquery.stellar.min.js') ?>"></script>
    <script src="<?= asset('app/js/owl.carousel.min.js') ?>"></script>
    <script src="<?= asset('app/js/jquery.magnific-popup.min.js0') ?>"></script>
    <script src="<?= asset('app/js/aos.js') ?>"></script>
    <script src="<?= asset('app/js/jquery.animateNumber.min.js') ?>"></script>
    <script src="<?= asset('app/js/bootstrap-datepicker.js') ?>"></script>
    <script src="<?= asset('app/js/jquery.timepicker.min.js') ?>"></script>
    <script src="<?= asset('app/js/scrollax.min.js') ?>"></script>
    <script src="<?= asset('app/https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false') ?>"></script>
    <script src="<?= asset('app/js/google-map.js') ?>"></script>
    <script src="<?= asset('app/js/main.js') ?>"></script>